# Generated by Django 5.0.6 on 2024-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('id_fase', models.BigIntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('id_profesor', models.IntegerField()),
            ],
        ),
    ]
