# Generated by Django 5.0.6 on 2024-07-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_materiales_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='titulo',
        ),
    ]
